import { TimelineEvent, TimelineEventType } from 'src/domain/timeline-event/timeline-event.entity';
import {
  CreateTimelineEventDTO,
  UpdateTimelineEventDTO,
  TimelineEventDTO,
} from 'src/presentation/timeline-event/timeline-event.dto';
import { TimelineEventDB } from 'src/infra/db/timeline-event-db/timeline-event-db.entity';

export function fromDTO(dto: TimelineEventDTO): TimelineEvent {
  return new TimelineEvent(
    dto.id,
    dto.year,
    dto.title,
    dto.description,
    dto.type as TimelineEventType,
    dto.image,
    dto.createdAt,
    dto.location,
  );
}

export function toDTO(entity: TimelineEvent): TimelineEventDTO {
  return new TimelineEventDTO(
    entity.id,
    entity.year,
    entity.title,
    entity.description,
    entity.type,
    entity.image,
    entity.createdAt,
    entity.location,
  );
}

export function fromCreateDTO(dto: CreateTimelineEventDTO): TimelineEvent {
  return new TimelineEvent(
    '', // ID will be generated by the service
    dto.year,
    dto.title,
    dto.description,
    dto.type as TimelineEventType,
    dto.image,
    new Date(), // Creation timestamp
    dto.location,
  );
}

export function fromUpdateDTO(existing: TimelineEvent, dto: UpdateTimelineEventDTO): TimelineEvent {
  return new TimelineEvent(
    existing.id,
    dto.year ?? existing.year,
    dto.title ?? existing.title,
    dto.description ?? existing.description,
    (dto.type as TimelineEventType) ?? existing.type,
    dto.image ?? existing.image,
    existing.createdAt, // Keep original creation date
    dto.location !== undefined ? dto.location : existing.location,
  );
}

export function toDB(entity: TimelineEvent): TimelineEventDB {
  const db = new TimelineEventDB();
  db.id = entity.id;
  db.year = entity.year;
  db.title = entity.title;
  db.description = entity.description;
  db.type = entity.type;
  db.location = entity.location;
  db.image = entity.image;
  db.createdAt = entity.createdAt;
  return db;
}

export function fromDB(db: TimelineEventDB): TimelineEvent {
  return new TimelineEvent(
    db.id,
    db.year,
    db.title,
    db.description,
    db.type as TimelineEventType,
    db.image,
    db.createdAt,
    db.location,
  );
}